// Shared city list — ~200 US cities sorted by population (highest-value markets first)
module.exports = [
  // Texas
  { city: 'Houston',          state: 'TX', stateFull: 'Texas' },
  { city: 'San Antonio',      state: 'TX', stateFull: 'Texas' },
  { city: 'Dallas',           state: 'TX', stateFull: 'Texas' },
  { city: 'Austin',           state: 'TX', stateFull: 'Texas' },
  { city: 'Fort Worth',       state: 'TX', stateFull: 'Texas' },
  { city: 'El Paso',          state: 'TX', stateFull: 'Texas' },
  { city: 'Arlington',        state: 'TX', stateFull: 'Texas' },
  { city: 'Corpus Christi',   state: 'TX', stateFull: 'Texas' },
  { city: 'Plano',            state: 'TX', stateFull: 'Texas' },
  { city: 'Lubbock',          state: 'TX', stateFull: 'Texas' },
  { city: 'Laredo',           state: 'TX', stateFull: 'Texas' },
  { city: 'Irving',           state: 'TX', stateFull: 'Texas' },
  { city: 'Garland',          state: 'TX', stateFull: 'Texas' },
  { city: 'Waco',             state: 'TX', stateFull: 'Texas' },
  { city: 'Frisco',           state: 'TX', stateFull: 'Texas' },
  { city: 'McKinney',         state: 'TX', stateFull: 'Texas' },
  { city: 'Amarillo',         state: 'TX', stateFull: 'Texas' },
  { city: 'Beaumont',         state: 'TX', stateFull: 'Texas' },
  { city: 'Killeen',          state: 'TX', stateFull: 'Texas' },
  // Florida
  { city: 'Jacksonville',     state: 'FL', stateFull: 'Florida' },
  { city: 'Miami',            state: 'FL', stateFull: 'Florida' },
  { city: 'Tampa',            state: 'FL', stateFull: 'Florida' },
  { city: 'Orlando',          state: 'FL', stateFull: 'Florida' },
  { city: 'St. Petersburg',   state: 'FL', stateFull: 'Florida' },
  { city: 'Fort Lauderdale',  state: 'FL', stateFull: 'Florida' },
  { city: 'Port St. Lucie',   state: 'FL', stateFull: 'Florida' },
  { city: 'Cape Coral',       state: 'FL', stateFull: 'Florida' },
  { city: 'Tallahassee',      state: 'FL', stateFull: 'Florida' },
  { city: 'Gainesville',      state: 'FL', stateFull: 'Florida' },
  { city: 'Pembroke Pines',   state: 'FL', stateFull: 'Florida' },
  { city: 'Pensacola',        state: 'FL', stateFull: 'Florida' },
  { city: 'Sarasota',         state: 'FL', stateFull: 'Florida' },
  { city: 'Fort Myers',       state: 'FL', stateFull: 'Florida' },
  { city: 'Lakeland',         state: 'FL', stateFull: 'Florida' },
  // California
  { city: 'Los Angeles',      state: 'CA', stateFull: 'California' },
  { city: 'San Diego',        state: 'CA', stateFull: 'California' },
  { city: 'San Jose',         state: 'CA', stateFull: 'California' },
  { city: 'San Francisco',    state: 'CA', stateFull: 'California' },
  { city: 'Fresno',           state: 'CA', stateFull: 'California' },
  { city: 'Sacramento',       state: 'CA', stateFull: 'California' },
  { city: 'Long Beach',       state: 'CA', stateFull: 'California' },
  { city: 'Bakersfield',      state: 'CA', stateFull: 'California' },
  { city: 'Oakland',          state: 'CA', stateFull: 'California' },
  { city: 'Anaheim',          state: 'CA', stateFull: 'California' },
  { city: 'Riverside',        state: 'CA', stateFull: 'California' },
  { city: 'Stockton',         state: 'CA', stateFull: 'California' },
  { city: 'Modesto',          state: 'CA', stateFull: 'California' },
  { city: 'Fontana',          state: 'CA', stateFull: 'California' },
  // Georgia
  { city: 'Atlanta',          state: 'GA', stateFull: 'Georgia' },
  { city: 'Columbus',         state: 'GA', stateFull: 'Georgia' },
  { city: 'Augusta',          state: 'GA', stateFull: 'Georgia' },
  { city: 'Savannah',         state: 'GA', stateFull: 'Georgia' },
  { city: 'Athens',           state: 'GA', stateFull: 'Georgia' },
  { city: 'Macon',            state: 'GA', stateFull: 'Georgia' },
  { city: 'Roswell',          state: 'GA', stateFull: 'Georgia' },
  // North Carolina
  { city: 'Charlotte',        state: 'NC', stateFull: 'North Carolina' },
  { city: 'Raleigh',          state: 'NC', stateFull: 'North Carolina' },
  { city: 'Greensboro',       state: 'NC', stateFull: 'North Carolina' },
  { city: 'Durham',           state: 'NC', stateFull: 'North Carolina' },
  { city: 'Winston-Salem',    state: 'NC', stateFull: 'North Carolina' },
  { city: 'Fayetteville',     state: 'NC', stateFull: 'North Carolina' },
  { city: 'Cary',             state: 'NC', stateFull: 'North Carolina' },
  { city: 'Wilmington',       state: 'NC', stateFull: 'North Carolina' },
  { city: 'Asheville',        state: 'NC', stateFull: 'North Carolina' },
  // Arizona
  { city: 'Phoenix',          state: 'AZ', stateFull: 'Arizona' },
  { city: 'Tucson',           state: 'AZ', stateFull: 'Arizona' },
  { city: 'Mesa',             state: 'AZ', stateFull: 'Arizona' },
  { city: 'Chandler',         state: 'AZ', stateFull: 'Arizona' },
  { city: 'Scottsdale',       state: 'AZ', stateFull: 'Arizona' },
  { city: 'Gilbert',          state: 'AZ', stateFull: 'Arizona' },
  { city: 'Tempe',            state: 'AZ', stateFull: 'Arizona' },
  { city: 'Peoria',           state: 'AZ', stateFull: 'Arizona' },
  { city: 'Surprise',         state: 'AZ', stateFull: 'Arizona' },
  // Tennessee
  { city: 'Nashville',        state: 'TN', stateFull: 'Tennessee' },
  { city: 'Memphis',          state: 'TN', stateFull: 'Tennessee' },
  { city: 'Knoxville',        state: 'TN', stateFull: 'Tennessee' },
  { city: 'Chattanooga',      state: 'TN', stateFull: 'Tennessee' },
  { city: 'Clarksville',      state: 'TN', stateFull: 'Tennessee' },
  { city: 'Murfreesboro',     state: 'TN', stateFull: 'Tennessee' },
  // Colorado
  { city: 'Denver',           state: 'CO', stateFull: 'Colorado' },
  { city: 'Colorado Springs', state: 'CO', stateFull: 'Colorado' },
  { city: 'Aurora',           state: 'CO', stateFull: 'Colorado' },
  { city: 'Fort Collins',     state: 'CO', stateFull: 'Colorado' },
  { city: 'Lakewood',         state: 'CO', stateFull: 'Colorado' },
  { city: 'Thornton',         state: 'CO', stateFull: 'Colorado' },
  { city: 'Pueblo',           state: 'CO', stateFull: 'Colorado' },
  // Ohio
  { city: 'Columbus',         state: 'OH', stateFull: 'Ohio' },
  { city: 'Cleveland',        state: 'OH', stateFull: 'Ohio' },
  { city: 'Cincinnati',       state: 'OH', stateFull: 'Ohio' },
  { city: 'Toledo',           state: 'OH', stateFull: 'Ohio' },
  { city: 'Akron',            state: 'OH', stateFull: 'Ohio' },
  { city: 'Dayton',           state: 'OH', stateFull: 'Ohio' },
  // Virginia
  { city: 'Virginia Beach',   state: 'VA', stateFull: 'Virginia' },
  { city: 'Norfolk',          state: 'VA', stateFull: 'Virginia' },
  { city: 'Chesapeake',       state: 'VA', stateFull: 'Virginia' },
  { city: 'Richmond',         state: 'VA', stateFull: 'Virginia' },
  { city: 'Newport News',     state: 'VA', stateFull: 'Virginia' },
  { city: 'Alexandria',       state: 'VA', stateFull: 'Virginia' },
  { city: 'Roanoke',          state: 'VA', stateFull: 'Virginia' },
  // Nevada
  { city: 'Las Vegas',        state: 'NV', stateFull: 'Nevada' },
  { city: 'Henderson',        state: 'NV', stateFull: 'Nevada' },
  { city: 'Reno',             state: 'NV', stateFull: 'Nevada' },
  { city: 'North Las Vegas',  state: 'NV', stateFull: 'Nevada' },
  // Illinois
  { city: 'Chicago',          state: 'IL', stateFull: 'Illinois' },
  { city: 'Aurora',           state: 'IL', stateFull: 'Illinois' },
  { city: 'Naperville',       state: 'IL', stateFull: 'Illinois' },
  { city: 'Rockford',         state: 'IL', stateFull: 'Illinois' },
  { city: 'Springfield',      state: 'IL', stateFull: 'Illinois' },
  { city: 'Joliet',           state: 'IL', stateFull: 'Illinois' },
  { city: 'Peoria',           state: 'IL', stateFull: 'Illinois' },
  // Michigan
  { city: 'Detroit',          state: 'MI', stateFull: 'Michigan' },
  { city: 'Grand Rapids',     state: 'MI', stateFull: 'Michigan' },
  { city: 'Warren',           state: 'MI', stateFull: 'Michigan' },
  { city: 'Lansing',          state: 'MI', stateFull: 'Michigan' },
  { city: 'Ann Arbor',        state: 'MI', stateFull: 'Michigan' },
  { city: 'Sterling Heights', state: 'MI', stateFull: 'Michigan' },
  // South Carolina
  { city: 'Columbia',         state: 'SC', stateFull: 'South Carolina' },
  { city: 'Charleston',       state: 'SC', stateFull: 'South Carolina' },
  { city: 'Greenville',       state: 'SC', stateFull: 'South Carolina' },
  { city: 'North Charleston', state: 'SC', stateFull: 'South Carolina' },
  // Indiana
  { city: 'Indianapolis',     state: 'IN', stateFull: 'Indiana' },
  { city: 'Fort Wayne',       state: 'IN', stateFull: 'Indiana' },
  { city: 'Evansville',       state: 'IN', stateFull: 'Indiana' },
  { city: 'South Bend',       state: 'IN', stateFull: 'Indiana' },
  { city: 'Carmel',           state: 'IN', stateFull: 'Indiana' },
  // Washington
  { city: 'Seattle',          state: 'WA', stateFull: 'Washington' },
  { city: 'Spokane',          state: 'WA', stateFull: 'Washington' },
  { city: 'Tacoma',           state: 'WA', stateFull: 'Washington' },
  { city: 'Vancouver',        state: 'WA', stateFull: 'Washington' },
  { city: 'Bellevue',         state: 'WA', stateFull: 'Washington' },
  { city: 'Everett',          state: 'WA', stateFull: 'Washington' },
  // Missouri
  { city: 'Kansas City',      state: 'MO', stateFull: 'Missouri' },
  { city: 'St. Louis',        state: 'MO', stateFull: 'Missouri' },
  { city: 'Springfield',      state: 'MO', stateFull: 'Missouri' },
  { city: 'Columbia',         state: 'MO', stateFull: 'Missouri' },
  // Minnesota
  { city: 'Minneapolis',      state: 'MN', stateFull: 'Minnesota' },
  { city: 'St. Paul',         state: 'MN', stateFull: 'Minnesota' },
  { city: 'Rochester',        state: 'MN', stateFull: 'Minnesota' },
  // Pennsylvania
  { city: 'Philadelphia',     state: 'PA', stateFull: 'Pennsylvania' },
  { city: 'Pittsburgh',       state: 'PA', stateFull: 'Pennsylvania' },
  { city: 'Allentown',        state: 'PA', stateFull: 'Pennsylvania' },
  { city: 'Erie',             state: 'PA', stateFull: 'Pennsylvania' },
  { city: 'Reading',          state: 'PA', stateFull: 'Pennsylvania' },
  // Maryland
  { city: 'Baltimore',        state: 'MD', stateFull: 'Maryland' },
  { city: 'Frederick',        state: 'MD', stateFull: 'Maryland' },
  { city: 'Rockville',        state: 'MD', stateFull: 'Maryland' },
  { city: 'Gaithersburg',     state: 'MD', stateFull: 'Maryland' },
  // Kentucky
  { city: 'Louisville',       state: 'KY', stateFull: 'Kentucky' },
  { city: 'Lexington',        state: 'KY', stateFull: 'Kentucky' },
  { city: 'Bowling Green',    state: 'KY', stateFull: 'Kentucky' },
  // Alabama
  { city: 'Birmingham',       state: 'AL', stateFull: 'Alabama' },
  { city: 'Huntsville',       state: 'AL', stateFull: 'Alabama' },
  { city: 'Montgomery',       state: 'AL', stateFull: 'Alabama' },
  { city: 'Mobile',           state: 'AL', stateFull: 'Alabama' },
  // Oklahoma
  { city: 'Oklahoma City',    state: 'OK', stateFull: 'Oklahoma' },
  { city: 'Tulsa',            state: 'OK', stateFull: 'Oklahoma' },
  { city: 'Norman',           state: 'OK', stateFull: 'Oklahoma' },
  { city: 'Broken Arrow',     state: 'OK', stateFull: 'Oklahoma' },
  // Oregon
  { city: 'Portland',         state: 'OR', stateFull: 'Oregon' },
  { city: 'Salem',            state: 'OR', stateFull: 'Oregon' },
  { city: 'Eugene',           state: 'OR', stateFull: 'Oregon' },
  { city: 'Gresham',          state: 'OR', stateFull: 'Oregon' },
  // Utah
  { city: 'Salt Lake City',   state: 'UT', stateFull: 'Utah' },
  { city: 'West Valley City', state: 'UT', stateFull: 'Utah' },
  { city: 'Provo',            state: 'UT', stateFull: 'Utah' },
  { city: 'West Jordan',      state: 'UT', stateFull: 'Utah' },
  { city: 'Orem',             state: 'UT', stateFull: 'Utah' },
  // Louisiana
  { city: 'New Orleans',      state: 'LA', stateFull: 'Louisiana' },
  { city: 'Baton Rouge',      state: 'LA', stateFull: 'Louisiana' },
  { city: 'Shreveport',       state: 'LA', stateFull: 'Louisiana' },
  { city: 'Lafayette',        state: 'LA', stateFull: 'Louisiana' },
  { city: 'Metairie',         state: 'LA', stateFull: 'Louisiana' },
  // Kansas
  { city: 'Wichita',          state: 'KS', stateFull: 'Kansas' },
  { city: 'Overland Park',    state: 'KS', stateFull: 'Kansas' },
  { city: 'Topeka',           state: 'KS', stateFull: 'Kansas' },
  // Nebraska
  { city: 'Omaha',            state: 'NE', stateFull: 'Nebraska' },
  { city: 'Lincoln',          state: 'NE', stateFull: 'Nebraska' },
  // Wisconsin
  { city: 'Milwaukee',        state: 'WI', stateFull: 'Wisconsin' },
  { city: 'Madison',          state: 'WI', stateFull: 'Wisconsin' },
  { city: 'Green Bay',        state: 'WI', stateFull: 'Wisconsin' },
  // New Mexico
  { city: 'Albuquerque',      state: 'NM', stateFull: 'New Mexico' },
  { city: 'Las Cruces',       state: 'NM', stateFull: 'New Mexico' },
  { city: 'Rio Rancho',       state: 'NM', stateFull: 'New Mexico' },
  // Idaho
  { city: 'Boise',            state: 'ID', stateFull: 'Idaho' },
  { city: 'Meridian',         state: 'ID', stateFull: 'Idaho' },
  { city: 'Nampa',            state: 'ID', stateFull: 'Idaho' },
  // Arkansas
  { city: 'Little Rock',      state: 'AR', stateFull: 'Arkansas' },
  { city: 'Fort Smith',       state: 'AR', stateFull: 'Arkansas' },
  { city: 'Fayetteville',     state: 'AR', stateFull: 'Arkansas' },
  { city: 'Jonesboro',        state: 'AR', stateFull: 'Arkansas' },
  // Mississippi
  { city: 'Jackson',          state: 'MS', stateFull: 'Mississippi' },
  { city: 'Gulfport',         state: 'MS', stateFull: 'Mississippi' },
  { city: 'Southaven',        state: 'MS', stateFull: 'Mississippi' },
  // Iowa
  { city: 'Des Moines',       state: 'IA', stateFull: 'Iowa' },
  { city: 'Cedar Rapids',     state: 'IA', stateFull: 'Iowa' },
  { city: 'Sioux City',       state: 'IA', stateFull: 'Iowa' },
];
