// Egypt cities — sorted by market size (interior design density)
module.exports = [
  { city: 'Cairo',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Alexandria',          state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Giza',                state: 'Egypt', stateFull: 'Egypt' },
  { city: 'New Cairo',           state: 'Egypt', stateFull: 'Egypt' },
  { city: '6th of October City', state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Sharm El Sheikh',     state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Hurghada',            state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Luxor',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Aswan',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Mansoura',            state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Tanta',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Port Said',           state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Suez',                state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Ismailia',            state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Zagazig',             state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Damietta',            state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Asyut',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Minya',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Beni Suef',           state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Fayyum',              state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Sohag',               state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Qena',                state: 'Egypt', stateFull: 'Egypt' },
  { city: 'El Mahalla El Kubra', state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Damanhur',            state: 'Egypt', stateFull: 'Egypt' },
  { city: 'Kafr El Sheikh',      state: 'Egypt', stateFull: 'Egypt' },
];
